// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"
)

const cleanOldAccounts = `-- name: CleanOldAccounts :exec
DELETE FROM accounts
WHERE updated_at < datetime('now', '-7 days')
`

func (q *Queries) CleanOldAccounts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanOldAccounts)
	return err
}

const getAccountByNameTag = `-- name: GetAccountByNameTag :one
SELECT puuid, region, account_level, name, tag, card, title, updated_at, created_at FROM accounts
WHERE name = ? AND tag = ?
LIMIT 1
`

type GetAccountByNameTagParams struct {
	Name string `json:"name"`
	Tag  string `json:"tag"`
}

func (q *Queries) GetAccountByNameTag(ctx context.Context, arg GetAccountByNameTagParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByNameTag, arg.Name, arg.Tag)
	var i Account
	err := row.Scan(
		&i.Puuid,
		&i.Region,
		&i.AccountLevel,
		&i.Name,
		&i.Tag,
		&i.Card,
		&i.Title,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByPUUID = `-- name: GetAccountByPUUID :one
SELECT puuid, region, account_level, name, tag, card, title, updated_at, created_at FROM accounts
WHERE puuid = ?
LIMIT 1
`

func (q *Queries) GetAccountByPUUID(ctx context.Context, puuid string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByPUUID, puuid)
	var i Account
	err := row.Scan(
		&i.Puuid,
		&i.Region,
		&i.AccountLevel,
		&i.Name,
		&i.Tag,
		&i.Card,
		&i.Title,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAccount = `-- name: UpsertAccount :exec
INSERT INTO accounts (puuid, region, account_level, name, tag, card, title, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(puuid) DO UPDATE SET
    region = excluded.region,
    account_level = excluded.account_level,
    name = excluded.name,
    tag = excluded.tag,
    card = excluded.card,
    title = excluded.title,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertAccountParams struct {
	Puuid        string `json:"puuid"`
	Region       string `json:"region"`
	AccountLevel int64  `json:"account_level"`
	Name         string `json:"name"`
	Tag          string `json:"tag"`
	Card         string `json:"card"`
	Title        string `json:"title"`
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccount,
		arg.Puuid,
		arg.Region,
		arg.AccountLevel,
		arg.Name,
		arg.Tag,
		arg.Card,
		arg.Title,
	)
	return err
}
