// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Account struct {
	Puuid        string    `json:"puuid"`
	Region       string    `json:"region"`
	AccountLevel int64     `json:"account_level"`
	Name         string    `json:"name"`
	Tag          string    `json:"tag"`
	Card         string    `json:"card"`
	Title        string    `json:"title"`
	UpdatedAt    time.Time `json:"updated_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Client struct {
	ClientID      string    `json:"client_id"`
	LastHeartbeat time.Time `json:"last_heartbeat"`
	LcuAvailable  bool      `json:"lcu_available"`
	ConnectedAt   time.Time `json:"connected_at"`
	Version       string    `json:"version"`
}

type RequestLog struct {
	ID           int64     `json:"id"`
	RequestID    string    `json:"request_id"`
	ClientID     *string   `json:"client_id"`
	GameName     string    `json:"game_name"`
	GameTag      string    `json:"game_tag"`
	Puuid        *string   `json:"puuid"`
	Success      bool      `json:"success"`
	ErrorMessage *string   `json:"error_message"`
	DurationMs   *int64    `json:"duration_ms"`
	CreatedAt    time.Time `json:"created_at"`
}
