// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CleanOldAccounts(ctx context.Context) error
	CleanOldLogs(ctx context.Context) error
	CleanStaleClients(ctx context.Context) error
	GetAccountByNameTag(ctx context.Context, arg GetAccountByNameTagParams) (Account, error)
	GetAccountByPUUID(ctx context.Context, puuid string) (Account, error)
	GetAllClients(ctx context.Context) ([]Client, error)
	GetAvailableClients(ctx context.Context) ([]Client, error)
	GetRequestStats(ctx context.Context) (GetRequestStatsRow, error)
	LogRequest(ctx context.Context, arg LogRequestParams) error
	RegisterClient(ctx context.Context, arg RegisterClientParams) error
	RemoveClient(ctx context.Context, clientID string) error
	UpdateClientHeartbeat(ctx context.Context, arg UpdateClientHeartbeatParams) error
	UpsertAccount(ctx context.Context, arg UpsertAccountParams) error
}

var _ Querier = (*Queries)(nil)
