// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request_log.sql

package db

import (
	"context"
)

const cleanOldLogs = `-- name: CleanOldLogs :exec
DELETE FROM request_log
WHERE created_at < datetime('now', '-30 days')
`

func (q *Queries) CleanOldLogs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanOldLogs)
	return err
}

const getRequestStats = `-- name: GetRequestStats :one
SELECT
    COUNT(*) as total_requests,
    SUM(CASE WHEN success = TRUE THEN 1 ELSE 0 END) as successful_requests,
    AVG(duration_ms) as avg_duration_ms
FROM request_log
WHERE created_at > datetime('now', '-1 hour')
`

type GetRequestStatsRow struct {
	TotalRequests      int64    `json:"total_requests"`
	SuccessfulRequests *float64 `json:"successful_requests"`
	AvgDurationMs      *float64 `json:"avg_duration_ms"`
}

func (q *Queries) GetRequestStats(ctx context.Context) (GetRequestStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getRequestStats)
	var i GetRequestStatsRow
	err := row.Scan(&i.TotalRequests, &i.SuccessfulRequests, &i.AvgDurationMs)
	return i, err
}

const logRequest = `-- name: LogRequest :exec
INSERT INTO request_log (request_id, client_id, game_name, game_tag, puuid, success, error_message, duration_ms)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type LogRequestParams struct {
	RequestID    string  `json:"request_id"`
	ClientID     *string `json:"client_id"`
	GameName     string  `json:"game_name"`
	GameTag      string  `json:"game_tag"`
	Puuid        *string `json:"puuid"`
	Success      bool    `json:"success"`
	ErrorMessage *string `json:"error_message"`
	DurationMs   *int64  `json:"duration_ms"`
}

func (q *Queries) LogRequest(ctx context.Context, arg LogRequestParams) error {
	_, err := q.db.ExecContext(ctx, logRequest,
		arg.RequestID,
		arg.ClientID,
		arg.GameName,
		arg.GameTag,
		arg.Puuid,
		arg.Success,
		arg.ErrorMessage,
		arg.DurationMs,
	)
	return err
}
